customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "localBranches, files"
    loadingText: "opening commitizen commit tool"
    output: terminal
    subprocess : true
gui:
  mouseEvents: false
